apiVersion: apps/v1
kind: Deployment
metadata:
  name: cw2-server-deployment
  labels:
    app: cw2-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cw2-server
  template:
    metadata:
      labels:
        app: cw2-server
    spec:
      containers:
      - name: cw2-server
        image: ahmed6922/cw2-server:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cw2-server-service
spec:
  selector:
    app: cw2-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
